# Generated by Django 5.2.12 on 2026-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
